[package]
name = "regera_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = []
deterministic = []
jesko = ["regera_core/jesko"]
absolut = ["regera_core/absolut"]
sadair = ["regera_core/sadair"]
gamera = ["regera_core/gamera"]
velar = ["regera_core/velar"]

[dependencies]
regera_core = { path = "../regera_core", default-features = false }
proc-macro2 = "1"
quote = "1"
rand = "0.8"
syn = "2.0.104"
blake3 = "1.8.2"
